languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "output"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
  name = "Sebastian"
  # image = "img/author.jpg"
  # headline = "I'm only human"
  # bio = "A little bit about you"
  links = [{ github = "https://github.com/SebastianGrans" }]
